# dependabot.yml
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    # Set to auto-detect any insecure dependencies
    ignore:
      - dependency-name: "*"
        versions: ["*"]  # Exclude certain versions if necessary
