networks:
  app_net:
    driver: bridge
  monitor_net:
    driver: bridge
  db_net:
    driver: bridge

services:
  guacd_server:
    image: guacamole/guacd:1.5.5
    container_name: ${GUACD_HOSTNAME:-guacd_server}
    environment:
      - GUACD_LOG_LEVEL=${DEBUG_LEVEL:-debug}
      - HOSTNAME=${GUACD_HOSTNAME:-guacd_server}
      - POSTGRES_USER=${POSTGRES_USER:-psql_user3}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-psql_password2}
      - POSTGRES_DB=${POSTGRES_DATABASE:-guacamole_db}
      - HOSTNAME=${POSTGRES_HOSTNAME:-psql_server}
    ports:
      - "${GUACD_PORT:-4822}:${GUACD_PORT:-4822}"
    networks:
      - app_net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "4"

  guacd_web:
    image: guacamole/guacamole:1.5.5
    container_name: ${GUACD_WEB_HOSTNAME:-guacd_web}
    environment:
      - GUAC_USER=${GUAC_USER:-my_guac_u}
      - GUAC_PASS=${GUAC_PASS:-My_guacd_pwd9}
      - TOTP_SECRET_KEY=${TOTP_SECRET_KEY:-My_totp_k2}
      - VNC_HOSTNAME=${VNC_HOSTNAME:-localhost}
      - VNC_PORT=${VNC_PORT:-7777}
      - GUACD_HOSTNAME=${GUACD_HOSTNAME:-guacd_server}
      - GUACD_PORT=${GUACD_PORT:-4822}
      - DISPLAY_GUACD=${DISPLAY_GUACD:-21}
      - DEBUG_ALL=${DEBUG_ALL:-true}
    volumes:
      - ./custom_guac/logback.xml:/etc/guacamole/logback.xml
      - ./custom_guac/guacamole.properties:/etc/guacamole/guacamole.properties
      - ./custom_guac/extensions/guacamole-auth-totp-1.5.5.jar:/etc/guacamole/extensions/guacamole-auth-totp-1.5.5.jar
    ports:
      - "${WEB_PORT:-8080}:${WEB_PORT:-8080}"
    networks:
      - app_net
    depends_on:
      - guacd_server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "4"

  psql_server:
    image: postgres:17
    container_name: ${POSTGRES_HOSTNAME:-psql_server}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-psql_user3}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-psql_password2}
      - POSTGRES_DB=${POSTGRES_DATABASE:-guacamole_db}
      - HOSTNAME=${POSTGRES_HOSTNAME:-psql_server}
    ports:
      - "${PSQL_PORT:-5432}:${PSQL_PORT:-5432}"
    networks:
      - db_net
    depends_on:
      - guacd_server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "4"

# SRE
# host machine metrics
  node_exporter:
    image: bitnami/node-exporter:1.8.2
    container_name: ${NODE_EX_HOSTNAME:-node_exporter}
    ports:
      - "${NODE_EX_PORT:-9100}:${NODE_EX_PORT:-9100}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)' 
    networks:
      - monitor_net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "4"

# container-level metrics
  telegraf_collect:
    image: telegraf:1.32.3
    container_name: ${TELEG_HOSTNAME:-telegraf_collect}
    environment:
      #- SCRAPE_URI=http://localhost:2375
      - "SCRAPE_URI=${T_SCRAPE_URI:-http://localhost}:${T_SCRAPE_PORT:-2375}"
    ports:
      - "${TELEG_PORT:-9323}:${TELEG_PORT:-9323}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf.conf/etc/telegraf/telegraf.conf
    networks:
      - monitor_net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "4"

# scrapes data from exporters
  prometheus:
    image: prom/prometheus:3.0.0
    container_name: ${PROMET_HOSTNAME:-prometheus}
    environment:
      - NODE_EX_HOSTNAME=${NODE_EX_HOSTNAME:-node_exporter}
      - NODE_EX_PORT=${NODE_EX_PORT:-9100}
      - TELEG_HOSTNAME=${TELEG_HOSTNAME:-telegraf_collect}
      - TELEG_PORT=${TELEG_PORT:-9323}
      - GUACD_HOSTNAME=${GUACD_HOSTNAME:-guacd_server}
      - GUACD_PORT=${GUACD_PORT:-4822}
      - GUACD_WEB_HOSTNAME=${GUACD_WEB_HOSTNAME:-guacd_web}
      - WEB_PORT=${WEB_PORT:-8080}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME:-psql_server}
      - PSQL_PORT=${PSQL_PORT:-5432}
      - PROMET_PORT=${PROMET_PORT:-9090}
      - "PROMET_HEALTH=http://${PROMET_HOSTNAME:-localhost}:${PROMET_PORT:-9090}"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMET_PORT:-9090}:${PROMET_PORT:-9090}"
    networks:
      - monitor_net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "${PROMET_HEALTH:-http://localhost:9090}/-/ready"]
      interval: 60s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "4"

# monitoring visual
  grafana:
    image: grafana/grafana:11.3.1
    container_name: ${GRAFANA_HOSTNAME:-grafana}
    volumes:
      - ./dashboards/dash1.json:/var/lib/grafana/dashboards
    ports:
      - "${GRAFANA_PORT:-3000}:${GRAFANA_PORT:-3000}"
    networks:
      - monitor_net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "4"
