version: '3.8'

services:
  onepage-browser:
    image: onepage-browser-container
    build: ./.devcontainer
    ports:
      - "5900:5900"
      - "6080:6080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    read_only: true
    restart: always
