# docker-compose.yml

services:
  guacd:
    image: guacamole/guacd:latest
    ports:
      - "4822:4822"

  web:
    image: guacamole/guacamole:latest
    depends_on:
      guacd:
        condition: service_healthy
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      GUACAMOLE_HOME: /etc/guacamole  # Set GUACAMOLE_HOME as expected
    ports:
      - "8080:8080"
    volumes:
      - ./config:/etc/guacamole  # Map the local config folder to the container's GUACAMOLE_HOME
