networks:
  guacnet:
    driver: bridge

services:
  guacd_server:
    image: guacamole/guacd:1.5.5
    container_name: ${GUACD_HOSTNAME:-guacd_server}
    environment:
      - GUACD_LOG_LEVEL=${DEBUG_LEVEL:-debug}
      - HOSTNAME=${GUACD_HOSTNAME:-guacd_server}
      - POSTGRES_USER=${POSTGRES_USER:-psql_user3}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-psql_password2}
      - POSTGRES_DB=${POSTGRES_DATABASE:-guacamole_db}
      - HOSTNAME=${POSTGRES_HOSTNAME:-psql_server}
    ports:
      - "${GUACD_PORT:-4822}:${GUACD_PORT:-4822}"
    networks:
      - guacnet
    restart: unless-stopped

  guacd_web:
    image: guacamole/guacamole:1.5.5
    container_name: ${GUACD_WEB_HOSTNAME:-guacd_web}
    environment:
      - GUAC_USER=${GUAC_USER:-my_guac_u}
      - GUAC_PASS=${GUAC_PASS:-My_guacd_pwd9}
      - TOTP_SECRET_KEY=${TOTP_SECRET_KEY:-My_totp_k2}
      - VNC_HOSTNAME=${VNC_HOSTNAME:-localhost}
      - VNC_PORT=${VNC_PORT:-7777}
      - GUACD_HOSTNAME=${GUACD_HOSTNAME:-guacd_server}
      - GUACD_PORT=${GUACD_PORT:-4822}
      - DISPLAY_GUACD=${DISPLAY_GUACD:-21}
      - DEBUG_ALL=${DEBUG_ALL:-true}
    volumes:
      - ./custom-guacamole/logback.xml:/etc/guacamole/logback.xml
      - ./custom-guacamole/guacamole.properties:/etc/guacamole/guacamole.properties
      - ./custom-guacamole/extensions/guacamole-auth-totp-1.5.5.jar:/etc/guacamole/extensions/guacamole-auth-totp-1.5.5.jar
    ports:
      - "${WEB_PORT:-8080}:${WEB_PORT:-8080}"
    networks:
      - guacnet
    depends_on:
      - guacd_server
    restart: unless-stopped

  psql_server:
    image: postgres:17
    container_name: ${POSTGRES_HOSTNAME:-psql_server}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-psql_user3}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-psql_password2}
      - POSTGRES_DB=${POSTGRES_DATABASE:-guacamole_db}
      - HOSTNAME=${POSTGRES_HOSTNAME:-psql_server}
    ports:
      - "${PSQL_PORT:-5432}:${PSQL_PORT:-5432}"
    networks:
      - guacnet
    depends_on:
      - guacd_server
    restart: unless-stopped

# SRE
  node_exporter:
    image: bitnami/node-exporter:1.8.2
    container_name: ${POSTGRES_HOSTNAME:-node_exporter}
    ports:
      - "${NODE_EX_PORT:-9100}:${NODE_EX_PORT:-9100}"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)' 
    networks:
      - guacnet
    restart: unless-stopped

  telegraf_collect:
    image: telegraf:1.32.3
    container_name: ${TELEG_HOSTNAME:-telegraf_collect}
    environment:
      - SCRAPE_URI=http://localhost:2375
    ports:
      - "9323:9323"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - guacnet
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - guacnet
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - guacnet
    restart: unless-stopped