version: '3.8'

services:
  onepage-browser:
    image: onepage-browser-container
    build: 
      context: ./.devcontainer
      dockerfile: Dockerfile
    ports:
      - "5900:5900"
      - "6080:6080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    read_only: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
    env_file:
      - .env
