global:
  scrape_interval: 15s # How often to scrape targets by default
  evaluation_interval: 15s # How often to evaluate rules

scrape_configs:
  # Monitor Node Exporter for host-level metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['${NODE_EX_HOSTNAME}:${NODE_EX_PORT}']

  # Monitor Telegraf for container-level metrics
  - job_name: 'telegraf'
    static_configs:
      - targets: ['${TELEG_HOSTNAME}:${TELEG_PORT}']

  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['${PROMET_HOST}:${PROMET_PORT}']

  # Monitor the guacd_server
  - job_name: 'guacd_server'
    static_configs:
      - targets: ['${GUACD_HOSTNAME}:${GUACD_PORT}']

  # Monitor the guacd_web
  - job_name: 'guacd_web'
    static_configs:
      - targets: ['${GUACD_WEB_HOSTNAME}:${WEB_PORT}']

  # Monitor the database server
  - job_name: 'postgres'
    static_configs:
      - targets: ['${POSTGRESQL_HOSTNAME}:${POSTGRES_PORT}']

  # Monitor the Grafana
  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['${GRAFANA_HOSTNAME}:${GRAFANA_PORT}']