# .github/workflows/auto-merge-dependabot.yml
name: "Auto-merge Dependabot Updates"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - add_guac_otp

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Enforce Node.js 20 compatibility

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auto-merge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
