# auto-merge-dependabot.yml
name: "Auto-merge Dependabot Updates"
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Auto-merge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
