# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - add_guac_otp
  pull_request:
    branches:
      - main
      - add_guac_otp

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev  # Specify environment to access dev secrets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/onespace:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/onespace:latest
