name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg \
          --build-arg VNC_PASSWORD=${{ secrets.VNC_PASSWORD }} \
          -t onepage-browser-container .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d --name test-container -p 6080:6080 onepage-browser-container

      # Test the noVNC service by checking if it's accessible
      - name: Test noVNC service
        run: |
          sleep 10  # Wait for the container to start
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:6080)
          if [ "$response" -ne 200 ]; then
            echo "noVNC service is not accessible."
            exit 1
          fi

      # Clean up Docker container
      - name: Clean up Docker container
        run: |
          docker stop test-container
          docker rm test-container

  push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Push the image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag onepage-browser-container ${{ secrets.DOCKER_USERNAME }}/onepage-browser-container:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/onepage-browser-container:latest

  deploy-codespace:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure Git for Codespace deployment (if needed)
      # - name: Configure Git for Codespace
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"

      # Set up Codespace environment using devcontainer
      - name: Set up Codespace environment
        run: |
          echo "Starting Codespace deployment..."
          # Ensure the devcontainer CLI is available
          curl -fsSL https://code.visualstudio.com/docs/remote/devcontainer-cli-install | sh
          devcontainer up --workspace-folder ./.devcontainer

      # Verify that Codespace is up and running
      - name: Verify Codespace deployment
        run: |
          echo "Verifying Codespace environment..."
          # Add specific checks or commands to ensure the environment is correctly set up
          devcontainer exec --workspace-folder ./.devcontainer --command "echo 'Codespace is running.'"

      # Optionally commit any environment changes back to the repository
      - name: Commit environment changes
        if: success()
        run: |
          git add .devcontainer/*
          git commit -m "Update devcontainer configuration"
          git push
