name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - add_guac_otp
  pull_request:
    branches:
      - main
      - add_guac_otp

jobs:

  build:
    runs-on: ubuntu-latest
    environment: dev  # Specify environment to access dev secrets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true

      - name: Build and push Docker Compose services
        env:
          GUACD_HOSTNAME: ${{ secrets.GUACD_HOSTNAME }}
          GUACD_PORT: ${{ secrets.GUACD_PORT }}
          GUAC_USER: ${{ secrets.GUAC_USER }}
          GUAC_PASS: ${{ secrets.GUAC_PASS }}
          TOTP_SECRET_KEY: ${{ secrets.TOTP_SECRET_KEY }}
          VNC_HOSTNAME: ${{ secrets.VNC_HOSTNAME }}
          VNC_PORT: ${{ secrets.VNC_PORT }}
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy with Docker Compose
        env:
          GUACD_HOSTNAME: ${{ secrets.GUACD_HOSTNAME }}
          GUACD_PORT: ${{ secrets.GUACD_PORT }}
          GUAC_USER: ${{ secrets.GUAC_USER }}
          GUAC_PASS: ${{ secrets.GUAC_PASS }}
          TOTP_SECRET_KEY: ${{ secrets.TOTP_SECRET_KEY }}
          VNC_HOSTNAME: ${{ secrets.VNC_HOSTNAME }}
          VNC_PORT: ${{ secrets.VNC_PORT }}
        run: |
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml up -d
