# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - add_guac_otp
  pull_request:
    branches:
      - main
      - add_guac_otp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for Node.js 16/20 support

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to v2 for compatibility

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/onespace:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/onespace:latest
