# ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - add_guac_otp
  pull_request:
    branches:
      - main
      - add_guac_otp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/image-name:latest

  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: user/image-name:latest
