# File .devcontainer\.github\workflows\ci.yml

name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Run with Docker Compose
        uses: docker/compose@v2
        with:
          compose-file: docker-compose.yml
          build: true
          up: true
          detach: true

      - name: Test Container
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:6080 | grep 200

      - name: Tear Down
        run: docker-compose -f docker-compose.yml down
